#pragma once

#define VERSION_MAJOR 0
#define VERSION_MINOR 0
#define VERSION_PATCH 1

#define SAMPLE_TIMER_MS_DEFAULT 50
#define SAMPLE_TIMER_MS_MAX 1000
#define SAMPLE_TIMER_MS_MIN 30

#define RENDER_TIMER_MS_DEFAULT 250
#define RENDER_TIMER_MS_MAX 1000
#define RENDER_TIMER_MS_MIN 100
